annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: |
    - name: Chart Source
      url: https://github.com/disafronov/helm-charts
    - name: Grafana
      url: https://github.com/grafana/grafana
    - name: Loki
      url: https://github.com/grafana/loki
    - name: Mimir
      url: https://github.com/grafana/mimir
    - name: Tempo
      url: https://github.com/grafana/tempo
apiVersion: v2
appVersion: latest
dependencies:
- alias: grafana
  condition: grafana.enabled
  name: grafana
  repository: https://grafana.github.io/helm-charts
  version: ^9.0.0
- alias: loki
  condition: loki.enabled
  name: loki
  repository: https://grafana.github.io/helm-charts
  version: ^6.30.0
- alias: mimir
  condition: mimir.enabled
  name: mimir-distributed
  repository: https://grafana.github.io/helm-charts
  version: ^5.3.0
- alias: tempo
  condition: tempo.enabled
  name: tempo
  repository: https://grafana.github.io/helm-charts
  version: ^1.21.1
description: Umbrella chart for a custom Loki, Grafana, Tempo and Mimir (Prometheus in future) stack. NOT FOR PRODUCTION!
home: https://github.com/disafronov/helm-charts/tree/master/charts/lgtp
# icon: https://artifacthub.io/image/b4fed1a7-6c8f-4945-b99d-096efa3e4116
keywords:
- monitoring
- traces
- metrics
- logs
maintainers:
- name: disafronov
name: lgtp
sources:
- https://disafronov.github.io/helm-charts
- https://github.com/grafana/grafana
- https://github.com/grafana/loki
- https://github.com/grafana/mimir
- https://github.com/grafana/tempo
type: application
version: 0.0.1
