{{- if or (not .Values.deploymentType) (eq .Values.deploymentType "Deployment") }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "default.fullname" . }}
  labels:
    {{- include "default.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ default 1 .Values.replicaCount }}
  {{- end }}
  {{- if .Values.deployStrategy }}
  strategy:
    type: {{ .Values.deployStrategy }}
    {{- if eq .Values.deployStrategy "RollingUpdate" }}
    rollingUpdate:
      maxSurge: {{ default 1 .Values.rollingUpdate.maxSurge }}
      maxUnavailable: {{ default 0 .Values.rollingUpdate.maxUnavailable }}
    {{- end }}
  {{- end }}
  {{- include "default.common-spec_pod" . | nindent 2 }}
      containers:
        - name: {{ .Chart.Name }}
          {{- include "default.common-spec_container" . | nindent 10 }}
          volumeMounts:
            - mountPath: {{ default "/tmp" .Values.tmpMountPath }}
              name: tmp
        {{- with .Values.sidecars }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      volumes:
        - name: tmp
          emptyDir:
{{- end }}
