{{- if or (not .Values.deploymentType) (ne .Values.deploymentType "StatefulSet") }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "default.fullname" . }}
  labels:
    {{- include "default.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: default
      protocol: TCP
      name: default
  selector:
    {{- include "default.selectorLabels" . | nindent 4 }}
{{- end }}
